%% Example
% [SampleTimes]
% 0=in seconds since [Patient] TestDate midnight
testDate = writeKeys{strcmp({writeKeys{:,1}}, 'Patient') & ...
                     strcmp({writeKeys{:,3}}, 'TestDate'), ...
                     4};
testTime = writeKeys{strcmp({writeKeys{:,1}}, 'Patient') & ...
                     strcmp({writeKeys{:,3}}, 'TestTime'), ...
                     4};
t1 = datetime([testDate ' 00:00:00.000'],     'Format', 'MM/dd/yy HH:mm:ss.SSS');
t2 = datetime([testDate ' ' testTime '.250'], 'Format', 'MM/dd/yy HH:mm:ss.SSS');
writeKeys = [writeKeys; ...
            {'SampleTimes', '', '0', sprintf('%1.3f', seconds(t2-t1))}];
