%% eeglabDemoDatasetConversion()
%
% Demo wrapper script for testing EEGlab (.set/.fdt) to
% Persyst (.lay/.dat) conversion
%
% Dependencies:
%   EEGlab
%     https://sccn.ucsd.edu/eeglab
%   inifilePersyst (adaption from inifile)
%     https://nl.mathworks.com/matlabcentral/fileexchange/2976-inifile
%   layread
%     https://nl.mathworks.com/matlabcentral/fileexchange/52346-read-persyst-lay-dat-files
%
%
% Author: maarten.schrooten@uzleuven.be, Nov 2018

%% Go to correct folder manually

%% Create test dataset in EEGlab format
createEEGlabDemoDataset(fullfile('.', 'Recordings', 'eeglabDemoDataset0.set'));
createEEGlabDemoDataset(fullfile('.', 'Recordings', 'eeglabDemoDataset7.set'));

%% Convert test dataset from EEGlab format to Persyst format
for dataType = [0 7]
    convertEEGlabToPersyst([fullfile('.', 'Recordings', 'eeglabDemoDataset') num2str(dataType) '.set'], struct(...
        'dataType',       num2str(dataType), ...
        'mainsFrequency', '50', ...
        'montages',       struct('name',     {'A MONTAGE', 'B MONTAGE'}, ...
                                 'channels', {[{'F3-Fz'                   'F3-Fz'}; ...
                                               {'Fz-F4'                   'Fz-F4'}; ...
                                               {'P3-Pz'                   'P3-Pz'}; ...
                                               {'Pz-P4'                   'Pz-P4'}; ...
                                               {'X1|0,0,0,70,(off),(off)' 'ECG'}; ...
                                               {'Fz+F3+F4+Pz+P3+P4'       'Avg'}] ...
                                              [{'F3-P3'                   'F3-P3'}; ...
                                               {'Fz-Pz'                   'Fz-Pz'}; ...
                                               {'F4-P4'                   'F4-P4'}; ...
                                               {'X1|0,0,0,70,(off),(off)' 'ECG'}]}), ...
        'firstName',      'TESTPATIENT', ...
        'middleName',     NaN, ...
        'lastName',       'KWS', ...
        'sex',            'M', ...
        'hand',           'R', ...
        'birthDate',      datetime('1989/02/25',              'InputFormat', 'yyyy/MM/dd',              'Format', 'MM/dd/yy'), ...
        'id',             '123-45-6789', ...
        'medicalRecordN', '78789832', ...
        'testDate',       datetime('2018/11/29',              'InputFormat', 'yyyy/MM/dd',              'Format', 'MM/dd/yy'), ...
        'testTime',       datetime('2018/11/29 14:25:35.150', 'InputFormat', 'yyyy/MM/dd HH:mm:ss.SSS', 'Format', 'HH:mm:ss'), ...
        'physician',      'UZL', ...
        'technician',     'UZL', ...
        'history',        NaN, ...
        'medications',    NaN, ...
        'comments1',      NaN, ...
        'comments2',      NaN));
end; clear dataType

%% Read converted dataset and check if it matches with the original
showPersystDataset(fullfile('.', 'Recordings', 'eeglabDemoDataset0.lay'));
showPersystDataset(fullfile('.', 'Recordings', 'eeglabDemoDataset7.lay'));
