% [EEG LASTCOM] = pop_export_persyst(EEG) - Export to Persyst .lay format
%
% Input Arguments:
% - EEG = EEGlab EEG dataset
%
% Output Arguments:
% - EEG = EEGlab EEG dataset
% - LASTCOM = last command (char)
%
%
% Author: maarten.schrooten@uzleuven.be, Oct 2018
%
% Licence: see licence.txt

% Changes:
% - 2018-12-01 version 1.0

function [EEG, LASTCOM] = pop_export_persyst(EEG)

%% Check function arguments
if nargin == 0
    % Missing argument
    error('UNEF:MissingArgument', 'Missing argument')
elseif nargin > 1
    % Too many arguments
    error('UNEF:TooManyArguments', 'Too many arguments')
elseif isempty(EEG.data)
    % No data
    error('UNEF:NoData', 'No EEG data')
end

%% Export (using EEG.filename|filepath as destination)
convertEEGlabToPersyst(EEG, struct(...
    'dataType',       '7', ...
    'mainsFrequency', NaN, ...
    'montages',       NaN, ...
    'firstName',      '', ...
    'middleName',     NaN, ...
    'lastName',       EEG.subject, ...
    'sex',            NaN, ...
    'hand',           NaN, ...
    'birthDate',      NaN, ...
    'id',             NaN, ...
    'medicalRecordN', NaN, ...
    'testDate',       NaN, ...
    'testTime',       NaN, ...
    'physician',      NaN, ...
    'technician',     NaN, ...
    'history',        NaN, ...
    'medications',    NaN, ...
    'comments1',      EEG.comments, ...
    'comments2',      sprintf('Setname=%s Group=%s Condition=%s Session=%s', EEG.setname, EEG.group, EEG.condition, EEG.session)));

%% Last command
LASTCOM = ['EEG = pop_export_persyst(' inputname(1) ');'];

%% End of function
end